---
- name: Perform Full System Updates on RHEL Servers
  hosts: rhel_servers
  become: yes
  vars:
    reboot_required: false
    log_file: "/var/log/ansible_yum_update.log"

  tasks:

    - name: Clean YUM cache
      ansible.builtin.command:
        cmd: yum clean all
      register: clean_cache
      changed_when: "'Cleaning repos' in clean_cache.stdout"

    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
      register: yum_update
      notify: "Check if reboot is needed"

    - name: Log update results
      ansible.builtin.blockinfile:
        path: "{{ log_file }}"
        create: yes
        block: |
          Update executed on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
          Hostname: {{ ansible_hostname }}
          Yum Output:
          {{ yum_update.stdout }}
      when: yum_update.changed

    - name: Check if reboot is required (RHEL-specific)
      ansible.builtin.shell:
        cmd: needs-restarting -r
      register: reboot_check
      changed_when: reboot_check.rc == 1

  handlers:
    - name: Check if reboot is needed
      ansible.builtin.set_fact:
        reboot_required: "{{ reboot_check.rc == 1 }}"

    - name: Reboot the server if necessary
      ansible.builtin.reboot:
        msg: "Rebooting after full system update"
        when: reboot_required
